"""Smart UI Resolver: Multi-strategy UI locator with native OCR fallback and coordinate-grounded invocation.

Resolves UI elements through a robust cascading pipeline:
1. UIAutomation Exact & Substring Match (Name, AutomationId)
2. Normalized Accelerator Match (e.g. '&Open' -> 'Open')
3. ControlType / Role-Constrained Filtering
4. Native Windows OCR Fallback (for Canvas, Electron, Flutter, and DirectX apps)
"""

import json
from typing import Optional, Dict, Any, List
from winterm.interaction.window_manager import WindowManager
from winterm.interaction.mouse import MouseEngine
from winterm.interaction.keyboard import KeyboardEngine
from winterm.interaction.ocr_engine import WindowsOCREngine
from winterm.interaction.screen import ScreenPerceptionEngine
from winterm.interaction.ui_automation import UIAutomationEngine


class SmartUIResolver:
    """Provides resilient multi-strategy element location and interaction for agents."""

    @classmethod
    def build_smart_click_command(
        cls,
        window_identifier: str,
        element_query: str,
        control_type: Optional[str] = None,
        language_tag: str = "en-US",
    ) -> str:
        """Generates PowerShell command attempting UIAutomation first, cascading to Native OCR if not found."""
        clean_target = window_identifier.replace("'", "''")
        clean_query = element_query.replace("'", "''")
        clean_ctrl = control_type.replace("'", "''") if control_type else ""
        clean_lang = language_tag.replace("'", "''")

        script = (
            f"{WindowManager.WIN32_WINDOW_HELPER}\n"
            f"{MouseEngine.WIN32_MOUSE_HEADER}\n"
            f"{ScreenPerceptionEngine.WIN32_SCREEN_HEADER}\n"
            f"{WindowsOCREngine.WINRT_OCR_HELPER}\n"
            "Add-Type -AssemblyName UIAutomationClient, UIAutomationTypes, System.Windows.Forms;\n"
            "$foundTitle = '';\n"
            f"$hWnd = [Win32WindowCore]::ResolveWindow('{clean_target}', [ref]$foundTitle);\n"
            "if ($hWnd -eq [IntPtr]::Zero) {\n"
            f"    @{{ Success = $False; Target = '{clean_target}'; Error = 'Window not found' }} | ConvertTo-Json -Compress;\n"
            "    exit 0;\n"
            "};\n"
            "[Win32WindowCore]::ForceForeground($hWnd) | Out-Null;\n"
            "Start-Sleep -Milliseconds 150;\n"
            f"$query = '{clean_query}';\n"
            f"$reqCtrl = '{clean_ctrl}';\n"
            "\n"
            "# -------------------------------------------------------------------------\n"
            "# STRATEGY 1: UIAutomation Tree Search\n"
            "# -------------------------------------------------------------------------\n"
            "$matchedElem = $null;\n"
            "try {\n"
            "    $root = [System.Windows.Automation.AutomationElement]::FromHandle($hWnd);\n"
            "    $descendants = $root.FindAll(\n"
            "        [System.Windows.Automation.TreeScope]::Descendants,\n"
            "        [System.Windows.Automation.Condition]::TrueCondition\n"
            "    );\n"
            "    foreach ($item in $descendants) {\n"
            "        try {\n"
            "            $cur = $item.Current;\n"
            "            $cType = $cur.ControlType.ProgrammaticName.Replace('ControlType.', '');\n"
            "            if ($reqCtrl -and $cType -ne $reqCtrl) { continue };\n"
            "            $nameNorm = if ($cur.Name) { $cur.Name.Replace('&', '').Trim() } else { '' };\n"
            "            $autoNorm = if ($cur.AutomationId) { $cur.AutomationId.Trim() } else { '' };\n"
            "            $qNorm = $query.Replace('&', '').Trim();\n"
            "            if ($nameNorm -eq $qNorm -or $autoNorm -eq $qNorm) {\n"
            "                $matchedElem = $item;\n"
            "                break;\n"
            "            };\n"
            "            if ($nameNorm -like \"*$qNorm*\" -or $autoNorm -like \"*$qNorm*\") {\n"
            "                if (-not $matchedElem) { $matchedElem = $item };\n"
            "            };\n"
            "        } catch {}\n"
            "    };\n"
            "} catch {};\n"
            "\n"
            "# If UIAutomation matched, invoke or coordinate-click\n"
            "if ($matchedElem) {\n"
            "    $invoked = $false;\n"
            "    $method = 'UIAutomation.InvokePattern';\n"
            "    try {\n"
            "        $pattern = $matchedElem.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern);\n"
            "        if ($pattern) {\n"
            "            $pattern.Invoke();\n"
            "            $invoked = $true;\n"
            "        };\n"
            "    } catch {};\n"
            "    if (-not $invoked) {\n"
            "        $method = 'UIAutomation.CoordinateClick';\n"
            "        $rc = $matchedElem.Current.BoundingRectangle;\n"
            "        $clickX = [int]($rc.X + ($rc.Width / 2));\n"
            "        $clickY = [int]($rc.Y + ($rc.Height / 2));\n"
            "        [Win32MouseCore]::SetCursorPos($clickX, $clickY) | Out-Null;\n"
            "        Start-Sleep -Milliseconds 80;\n"
            "        [Win32MouseCore]::mouse_event(0x02, 0, 0, 0, 0);\n"
            "        Start-Sleep -Milliseconds 40;\n"
            "        [Win32MouseCore]::mouse_event(0x04, 0, 0, 0, 0);\n"
            "    };\n"
            "    @{\n"
            "        Success = $True;\n"
            "        Strategy = 'UIAutomation';\n"
            "        Method = $method;\n"
            "        Element = $matchedElem.Current.Name;\n"
            "        ControlType = $matchedElem.Current.ControlType.ProgrammaticName.Replace('ControlType.', '');\n"
            "        AutomationId = $matchedElem.Current.AutomationId;\n"
            "        WindowTitle = $foundTitle;\n"
            "    } | ConvertTo-Json -Compress;\n"
            "    exit 0;\n"
            "};\n"
            "\n"
            "# -------------------------------------------------------------------------\n"
            "# STRATEGY 2: Native Windows OCR Fallback\n"
            "# -------------------------------------------------------------------------\n"
            "$rect = New-Object Win32WindowCore+RECT;\n"
            "[Win32WindowCore]::GetWindowRect($hWnd, [ref]$rect) | Out-Null;\n"
            "$w = [Math]::Max(10, $rect.Right - $rect.Left);\n"
            "$h = [Math]::Max(10, $rect.Bottom - $rect.Top);\n"
            "$tempOcr = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), ('winterm_smart_ocr_' + [System.Guid]::NewGuid().ToString('N') + '.png'));\n"
            "try {\n"
            "    $captured = [Win32ScreenCore]::CaptureScreen($tempOcr, $rect.Left, $rect.Top, $w, $h);\n"
            "    if (-not $captured -or -not (Test-Path $tempOcr)) {\n"
            "        @{ Success = $False; Strategy = 'OCR_Failed'; Error = 'Could not capture window bitmap for OCR fallback' } | ConvertTo-Json -Compress;\n"
            "        exit 0;\n"
            "    };\n"
            "    $file = Await-WinRT ([Windows.Storage.StorageFile]::GetFileFromPathAsync($tempOcr)) ([Windows.Storage.StorageFile]);\n"
            "    $stream = Await-WinRT ($file.OpenAsync(0)) ([Windows.Storage.Streams.IRandomAccessStream]);\n"
            "    $decoder = Await-WinRT ([Windows.Graphics.Imaging.BitmapDecoder]::CreateAsync($stream)) ([Windows.Graphics.Imaging.BitmapDecoder]);\n"
            "    $softwareBitmap = Await-WinRT ($decoder.GetSoftwareBitmapAsync()) ([Windows.Graphics.Imaging.SoftwareBitmap]);\n"
            "    $engine = [Windows.Media.Ocr.OcrEngine]::TryCreateFromUserProfileLanguages();\n"
            "    if (-not $engine) {\n"
            "        $null = [Windows.Globalization.Language, Windows.Globalization, ContentType = WindowsRuntime];\n"
            f"        $engine = [Windows.Media.Ocr.OcrEngine]::TryCreateFromLanguage([Windows.Globalization.Language]::new('{clean_lang}'));\n"
            "    };\n"
            "    $ocrResult = Await-WinRT ($engine.RecognizeAsync($softwareBitmap)) ([Windows.Media.Ocr.OcrResult]);\n"
            "    \n"
            "    $bestWord = $null;\n"
            "    foreach ($line in $ocrResult.Lines) {\n"
            "        foreach ($wItem in $line.Words) {\n"
            "            if ($wItem.Text -like \"*$query*\" -or $query -like \"*$($wItem.Text)*\") {\n"
            "                $bestWord = $wItem;\n"
            "                break;\n"
            "            };\n"
            "        };\n"
            "        if ($bestWord) { break };\n"
            "    };\n"
            "    \n"
            "    if ($bestWord) {\n"
            "        $rc = $bestWord.BoundingRect;\n"
            "        $clickX = [int]($rect.Left + $rc.X + ($rc.Width / 2));\n"
            "        $clickY = [int]($rect.Top + $rc.Y + ($rc.Height / 2));\n"
            "        [Win32MouseCore]::SetCursorPos($clickX, $clickY) | Out-Null;\n"
            "        Start-Sleep -Milliseconds 80;\n"
            "        [Win32MouseCore]::mouse_event(0x02, 0, 0, 0, 0);\n"
            "        Start-Sleep -Milliseconds 40;\n"
            "        [Win32MouseCore]::mouse_event(0x04, 0, 0, 0, 0);\n"
            "        @{\n"
            "            Success = $True;\n"
            "            Strategy = 'NativeWindowsOCR';\n"
            "            Method = 'OCR.CoordinateClick';\n"
            "            MatchedWord = $bestWord.Text;\n"
            "            ClickCoordinates = @{ X = $clickX; Y = $clickY };\n"
            "            WindowTitle = $foundTitle;\n"
            "        } | ConvertTo-Json -Compress;\n"
            "    } else {\n"
            "        @{\n"
            "            Success = $False;\n"
            "            Query = $query;\n"
            "            Error = 'Element not found via UIAutomation or Native Windows OCR';\n"
            "            WindowTitle = $foundTitle;\n"
            "        } | ConvertTo-Json -Compress;\n"
            "    };\n"
            "} catch {\n"
            "    @{ Success = $False; Error = $_.Exception.Message } | ConvertTo-Json -Compress;\n"
            "} finally {\n"
            "    try { if (Test-Path $tempOcr) { [System.IO.File]::Delete($tempOcr) } } catch {};\n"
            "}\n"
        )
        return script
