"""Smart UI Resolver: Multi-strategy UI locator with native OCR fallback and coordinate-grounded invocation.

Resolves UI elements through a robust cascading pipeline:
1. UIAutomation Exact & Substring Match (Name, AutomationId)
2. Normalized Accelerator Match (e.g. '&Open' -> 'Open')
3. ControlType / Role-Constrained Filtering
4. Native Windows OCR Fallback (for Canvas, Electron, Flutter, and DirectX apps)
"""

import json
from typing import Optional, Dict, Any, List
from winterm.interaction.window_manager import WindowManager
from winterm.interaction.mouse import MouseEngine
from winterm.interaction.keyboard import KeyboardEngine
from winterm.interaction.ocr_engine import WindowsOCREngine
from winterm.interaction.screen import ScreenPerceptionEngine
from winterm.interaction.ui_automation import UIAutomationEngine


class SmartUIResolver:
    """Provides resilient multi-strategy element location and interaction for agents."""

    @classmethod
    def build_smart_click_command(
        cls,
        window_identifier: str,
        element_query: str,
        control_type: Optional[str] = None,
        language_tag: str = "en-US",
    ) -> str:
        """Generates PowerShell command attempting UIAutomation first, cascading to Native OCR if not found."""
        clean_target = window_identifier.replace("'", "''")
        clean_query = element_query.replace("'", "''")
        clean_ctrl = control_type.replace("'", "''") if control_type else ""
        clean_lang = language_tag.replace("'", "''")

        script = (
            f"{WindowManager.WIN32_WINDOW_HELPER}\n"
            f"{MouseEngine.WIN32_MOUSE_HEADER}\n"
            f"{ScreenPerceptionEngine.WIN32_SCREEN_HEADER}\n"
            f"{WindowsOCREngine.WINRT_OCR_HELPER}\n"
            "Add-Type -AssemblyName UIAutomationClient, UIAutomationTypes, System.Windows.Forms;\n"
            "$foundTitle = '';\n"
            f"$hWnd = [Win32WindowCore]::ResolveWindow('{clean_target}', [ref]$foundTitle);\n"
            "if ($hWnd -eq [IntPtr]::Zero) {\n"
            f"    @{{ Success = $False; Target = '{clean_target}'; Error = 'Window not found' }} | ConvertTo-Json -Compress;\n"
            "    exit 0;\n"
            "};\n"
            f"$fgRes = [Win32WindowCore]::ForceForegroundVerified($hWnd);\n"
            "Start-Sleep -Milliseconds 150;\n"
            f"$query = '{clean_query}';\n"
            f"$reqCtrl = '{clean_ctrl}';\n"
            "\n"
            "# -------------------------------------------------------------------------\n"
            "# STRATEGY 1: UIAutomation Tree Search\n"
            "# -------------------------------------------------------------------------\n"
            "$matchedElem = $null;\n"
            "try {\n"
            "    $root = [System.Windows.Automation.AutomationElement]::FromHandle($hWnd);\n"
            "    if ($root) {\n"
            "        $descendants = $root.FindAll(\n"
            "            [System.Windows.Automation.TreeScope]::Descendants,\n"
            "            [System.Windows.Automation.Condition]::TrueCondition\n"
            "        );\n"
            "        foreach ($item in $descendants) {\n"
            "            try {\n"
            "                $cur = $item.Current;\n"
            "                $cType = $cur.ControlType.ProgrammaticName.Replace('ControlType.', '');\n"
            "                if ($reqCtrl -and $cType -ne $reqCtrl) { continue };\n"
            "                $nameNorm = if ($cur.Name) { $cur.Name.Replace('&', '').Trim() } else { '' };\n"
            "                $autoNorm = if ($cur.AutomationId) { $cur.AutomationId.Trim() } else { '' };\n"
            "                $qNorm = $query.Replace('&', '').Trim();\n"
            "                if ($nameNorm -eq $qNorm -or $autoNorm -eq $qNorm) {\n"
            "                    $matchedElem = $item;\n"
            "                    break;\n"
            "                };\n"
            "                if ($nameNorm -like \"*$qNorm*\" -or $autoNorm -like \"*$qNorm*\") {\n"
            "                    if (-not $matchedElem) { $matchedElem = $item };\n"
            "                };\n"
            "            } catch {}\n"
            "        };\n"
            "    }\n"
            "} catch {};\n"
            "\n"
            "# If UIAutomation matched, invoke or coordinate-click\n"
            "if ($matchedElem) {\n"
            "    $invoked = $false;\n"
            "    $method = 'UIAutomation.InvokePattern';\n"
            "    try {\n"
            "        $pattern = $matchedElem.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern);\n"
            "        if ($pattern) {\n"
            "            $pattern.Invoke();\n"
            "            $invoked = $true;\n"
            "        };\n"
            "    } catch {};\n"
            "    if (-not $invoked) {\n"
            "        $method = 'UIAutomation.ClickInWindow';\n"
            "        $rc = $matchedElem.Current.BoundingRectangle;\n"
            "        $rect2 = New-Object Win32WindowCore+RECT;\n"
            "        [Win32WindowCore]::GetWindowRect($hWnd, [ref]$rect2) | Out-Null;\n"
            "        $relX = [int]($rc.X - $rect2.Left + ($rc.Width / 2));\n"
            "        $relY = [int]($rc.Y - $rect2.Top + ($rc.Height / 2));\n"
            "        $cr = [Win32MouseCore]::ClickInWindow($hWnd, $relX, $relY, 0x0002, 0x0004, 1);\n"
            "        if (-not $cr.ClickedInCorrectWindow) { $method = 'UIAutomation.ClickInWindow.Blocked' };\n"
            "    };\n"
            "    @{\n"
            "        Success = $True;\n"
            "        Strategy = 'UIAutomation';\n"
            "        Method = $method;\n"
            "        Element = $matchedElem.Current.Name;\n"
            "        ControlType = $matchedElem.Current.ControlType.ProgrammaticName.Replace('ControlType.', '');\n"
            "        AutomationId = $matchedElem.Current.AutomationId;\n"
            "        WindowTitle = $foundTitle;\n"
            "        FocusConfirmed = $fgRes.FocusConfirmed;\n"
            "    } | ConvertTo-Json -Compress;\n"
            "    exit 0;\n"
            "};\n"
            "\n"
            "# -------------------------------------------------------------------------\n"
            "# STRATEGY 2: Native Windows OCR Fallback\n"
            "# -------------------------------------------------------------------------\n"
            "$rect = New-Object Win32WindowCore+RECT;\n"
            "[Win32WindowCore]::GetWindowRect($hWnd, [ref]$rect) | Out-Null;\n"
            "$w = [Math]::Max(10, $rect.Right - $rect.Left);\n"
            "$h = [Math]::Max(10, $rect.Bottom - $rect.Top);\n"
            "$tempOcr = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), ('winterm_smart_ocr_' + [System.Guid]::NewGuid().ToString('N') + '.png'));\n"
            "try {\n"
            "    $captured = [Win32ScreenCore]::CaptureScreen($tempOcr, $rect.Left, $rect.Top, $w, $h);\n"
            "    if (-not $captured -or -not (Test-Path $tempOcr)) {\n"
            f"        @{{ Success = $False; Strategy = 'OCR_Failed'; Error = 'Could not capture window bitmap for OCR fallback' }} | ConvertTo-Json -Compress;\n"
            "        exit 0;\n"
            "    };\n"
            "    $file = Await-WinRT ([Windows.Storage.StorageFile]::GetFileFromPathAsync($tempOcr)) ([Windows.Storage.StorageFile]);\n"
            "    $stream = Await-WinRT ($file.OpenAsync(0)) ([Windows.Storage.Streams.IRandomAccessStream]);\n"
            "    $decoder = Await-WinRT ([Windows.Graphics.Imaging.BitmapDecoder]::CreateAsync($stream)) ([Windows.Graphics.Imaging.BitmapDecoder]);\n"
            "    $softwareBitmap = Await-WinRT ($decoder.GetSoftwareBitmapAsync()) ([Windows.Graphics.Imaging.SoftwareBitmap]);\n"
            "    $engine = [Windows.Media.Ocr.OcrEngine]::TryCreateFromUserProfileLanguages();\n"
            "    if (-not $engine) {\n"
            "        $null = [Windows.Globalization.Language, Windows.Globalization, ContentType = WindowsRuntime];\n"
            f"        $engine = [Windows.Media.Ocr.OcrEngine]::TryCreateFromLanguage([Windows.Globalization.Language]::new('{clean_lang}'));\n"
            "    };\n"
            "    $ocrResult = Await-WinRT ($engine.RecognizeAsync($softwareBitmap)) ([Windows.Media.Ocr.OcrResult]);\n"
            "    \n"
            "    $targetRect = $null;\n"
            "    $matchedLabel = '';\n"
            "    # Check 2a: Phrase / line-level match\n"
            "    foreach ($line in $ocrResult.Lines) {\n"
            "        if ($line.Text -like \"*$query*\" -or $query -like \"*$($line.Text)*\") {\n"
            "            $minX = $w; $minY = $h; $maxX = 0; $maxY = 0;\n"
            "            foreach ($wItem in $line.Words) {\n"
            "                $wrc = $wItem.BoundingRect;\n"
            "                if ($wrc.X -lt $minX) { $minX = [int]$wrc.X };\n"
            "                if ($wrc.Y -lt $minY) { $minY = [int]$wrc.Y };\n"
            "                if (($wrc.X + $wrc.Width) -gt $maxX) { $maxX = [int]($wrc.X + $wrc.Width) };\n"
            "                if (($wrc.Y + $wrc.Height) -gt $maxY) { $maxY = [int]($wrc.Y + $wrc.Height) };\n"
            "            };\n"
            "            $targetRect = @{ X = $minX; Y = $minY; Width = ($maxX - $minX); Height = ($maxY - $minY) };\n"
            "            $matchedLabel = $line.Text;\n"
            "            break;\n"
            "        };\n"
            "    };\n"
            "    # Check 2b: Word-level substring match\n"
            "    if (-not $targetRect) {\n"
            "        foreach ($line in $ocrResult.Lines) {\n"
            "            foreach ($wItem in $line.Words) {\n"
            "                if ($wItem.Text -like \"*$query*\" -or $query -like \"*$($wItem.Text)*\") {\n"
            "                    $wrc = $wItem.BoundingRect;\n"
            "                    $targetRect = @{ X = [int]$wrc.X; Y = [int]$wrc.Y; Width = [int]$wrc.Width; Height = [int]$wrc.Height };\n"
            "                    $matchedLabel = $wItem.Text;\n"
            "                    break;\n"
            "                };\n"
            "            };\n"
            "            if ($targetRect) { break };\n"
            "        };\n"
            "    };\n"
            "    \n"
            "    if ($targetRect) {\n"
            "        $relX = [int]($targetRect.X + ($targetRect.Width / 2));\n"
            "        $relY = [int]($targetRect.Y + ($targetRect.Height / 2));\n"
            "        $clickResult = [Win32MouseCore]::ClickInWindow($hWnd, $relX, $relY, 0x0002, 0x0004, 1);\n"
            "        @{\n"
            "            Success = $clickResult.Success;\n"
            "            Strategy = 'NativeWindowsOCR';\n"
            "            Method = 'OCR.ClickInWindow';\n"
            "            ClickedInCorrectWindow = $clickResult.ClickedInCorrectWindow;\n"
            "            MatchedWord = $matchedLabel;\n"
            "            RelCoordinates = @{ X = $relX; Y = $relY };\n"
            "            AbsCoordinates = @{ X = $clickResult.AbsX; Y = $clickResult.AbsY };\n"
            "            WindowTitle = $foundTitle;\n"
            "            FocusConfirmed = $fgRes.FocusConfirmed;\n"
            "            Error = $clickResult.Error;\n"
            "        } | ConvertTo-Json -Compress;\n"
            "    } else {\n"
            "        @{\n"
            "            Success = $False;\n"
            "            Query = $query;\n"
            "            Error = 'Element not found via UIAutomation or Native Windows OCR';\n"
            "            WindowTitle = $foundTitle;\n"
            "            FocusConfirmed = $fgRes.FocusConfirmed;\n"
            "        } | ConvertTo-Json -Compress;\n"
            "    };\n"
            "} catch {\n"
            "    @{ Success = $False; Error = $_.Exception.Message } | ConvertTo-Json -Compress;\n"
            "} finally {\n"
            "    try { if (Test-Path $tempOcr) { [System.IO.File]::Delete($tempOcr) } } catch {};\n"
            "}\n"
        )
        return script

    @classmethod
    def build_smart_hover_command(
        cls,
        window_identifier: str,
        element_query: Optional[str] = None,
        rel_x: Optional[int] = None,
        rel_y: Optional[int] = None,
        dwell_ms: int = 500,
        control_type: Optional[str] = None,
        language_tag: str = "en-US",
    ) -> str:
        """Generates PowerShell command to hover over a target UI element (via UIA/OCR) or relative coordinates."""
        clean_target = window_identifier.replace("'", "''")
        clean_query = (element_query or "").replace("'", "''")
        clean_ctrl = control_type.replace("'", "''") if control_type else ""
        clean_lang = language_tag.replace("'", "''")

        if rel_x is not None and rel_y is not None and not element_query:
            # Direct coordinate hover within window
            script = (
                f"{WindowManager.WIN32_WINDOW_HELPER}\n"
                f"{MouseEngine.WIN32_MOUSE_HEADER}\n"
                "$foundTitle = '';\n"
                f"$hWnd = [Win32WindowCore]::ResolveWindow('{clean_target}', [ref]$foundTitle);\n"
                "if ($hWnd -eq [IntPtr]::Zero) {\n"
                f"    @{{ Success = $False; Target = '{clean_target}'; Error = 'Window not found' }} | ConvertTo-Json -Compress;\n"
                "    exit 0;\n"
                "};\n"
                f"$fgRes = [Win32WindowCore]::ForceForegroundVerified($hWnd);\n"
                "Start-Sleep -Milliseconds 100;\n"
                f"$hoverRes = [Win32MouseCore]::HoverInWindow($hWnd, {int(rel_x)}, {int(rel_y)}, {int(dwell_ms)});\n"
                "@{\n"
                "    Success = $hoverRes.Success;\n"
                "    Strategy = 'DirectCoordinates';\n"
                "    HoveredInCorrectWindow = $hoverRes.HoveredInCorrectWindow;\n"
                f"    RelCoordinates = @{{ X = {int(rel_x)}; Y = {int(rel_y)} }};\n"
                "    AbsCoordinates = @{ X = $hoverRes.AbsX; Y = $hoverRes.AbsY };\n"
                "    WindowTitle = $foundTitle;\n"
                "    FocusConfirmed = $fgRes.FocusConfirmed;\n"
                "    Error = $hoverRes.Error;\n"
                "} | ConvertTo-Json -Compress;\n"
            )
            return script

        # Query-based smart hover
        script = (
            f"{WindowManager.WIN32_WINDOW_HELPER}\n"
            f"{MouseEngine.WIN32_MOUSE_HEADER}\n"
            f"{ScreenPerceptionEngine.WIN32_SCREEN_HEADER}\n"
            f"{WindowsOCREngine.WINRT_OCR_HELPER}\n"
            "Add-Type -AssemblyName UIAutomationClient, UIAutomationTypes, System.Windows.Forms;\n"
            "$foundTitle = '';\n"
            f"$hWnd = [Win32WindowCore]::ResolveWindow('{clean_target}', [ref]$foundTitle);\n"
            "if ($hWnd -eq [IntPtr]::Zero) {\n"
            f"    @{{ Success = $False; Target = '{clean_target}'; Error = 'Window not found' }} | ConvertTo-Json -Compress;\n"
            "    exit 0;\n"
            "};\n"
            f"$fgRes = [Win32WindowCore]::ForceForegroundVerified($hWnd);\n"
            "Start-Sleep -Milliseconds 150;\n"
            f"$query = '{clean_query}';\n"
            f"$reqCtrl = '{clean_ctrl}';\n"
            f"$dwell = {int(dwell_ms)};\n"
            "\n"
            "# -------------------------------------------------------------------------\n"
            "# STRATEGY 1: UIAutomation Tree Search\n"
            "# -------------------------------------------------------------------------\n"
            "$matchedElem = $null;\n"
            "try {\n"
            "    $root = [System.Windows.Automation.AutomationElement]::FromHandle($hWnd);\n"
            "    if ($root) {\n"
            "        $condTrue = [System.Windows.Automation.Condition]::TrueCondition;\n"
            "        $allElements = $root.FindAll([System.Windows.Automation.TreeScope]::Descendants, $condTrue);\n"
            "        foreach ($el in $allElements) {\n"
            "            try {\n"
            "                $nm = $el.Current.Name;\n"
            "                $aid = $el.Current.AutomationId;\n"
            "                $ct = $el.Current.ControlType.ProgrammaticName.Replace('ControlType.', '');\n"
            "                if ($reqCtrl -and ($ct -ne $reqCtrl)) { continue };\n"
            "                $cleanNm = $nm -replace '&', '';\n"
            "                if (($nm -and ($nm -eq $query -or $cleanNm -eq $query)) -or ($aid -and ($aid -eq $query))) {\n"
            "                    $matchedElem = $el; break;\n"
            "                };\n"
            "            } catch {}\n"
            "        };\n"
            "        if (-not $matchedElem) {\n"
            "            foreach ($el in $allElements) {\n"
            "                try {\n"
            "                    $nm = $el.Current.Name;\n"
            "                    $aid = $el.Current.AutomationId;\n"
            "                    $ct = $el.Current.ControlType.ProgrammaticName.Replace('ControlType.', '');\n"
            "                    if ($reqCtrl -and ($ct -ne $reqCtrl)) { continue };\n"
            "                    if (($nm -and $nm.IndexOf($query, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) -or ($aid -and $aid.IndexOf($query, [System.StringComparison]::OrdinalIgnoreCase) -ge 0)) {\n"
            "                        $matchedElem = $el; break;\n"
            "                    };\n"
            "                } catch {}\n"
            "            };\n"
            "        };\n"
            "    }\n"
            "} catch {};\n"
            "\n"
            "# If UIAutomation matched, hover over center of element\n"
            "if ($matchedElem) {\n"
            "    $rc = $matchedElem.Current.BoundingRectangle;\n"
            "    $rect2 = New-Object Win32WindowCore+RECT;\n"
            "    [Win32WindowCore]::GetWindowRect($hWnd, [ref]$rect2) | Out-Null;\n"
            "    $relX = [int]($rc.X - $rect2.Left + ($rc.Width / 2));\n"
            "    $relY = [int]($rc.Y - $rect2.Top + ($rc.Height / 2));\n"
            "    $hr = [Win32MouseCore]::HoverInWindow($hWnd, $relX, $relY, $dwell);\n"
            "    @{\n"
            "        Success = $hr.Success;\n"
            "        Strategy = 'UIAutomation';\n"
            "        HoveredInCorrectWindow = $hr.HoveredInCorrectWindow;\n"
            "        Element = $matchedElem.Current.Name;\n"
            "        ControlType = $matchedElem.Current.ControlType.ProgrammaticName.Replace('ControlType.', '');\n"
            "        RelCoordinates = @{ X = $relX; Y = $relY };\n"
            "        AbsCoordinates = @{ X = $hr.AbsX; Y = $hr.AbsY };\n"
            "        WindowTitle = $foundTitle;\n"
            "        FocusConfirmed = $fgRes.FocusConfirmed;\n"
            "        Error = $hr.Error;\n"
            "    } | ConvertTo-Json -Compress;\n"
            "    exit 0;\n"
            "};\n"
            "\n"
            "# -------------------------------------------------------------------------\n"
            "# STRATEGY 2: Native Windows OCR Fallback\n"
            "# -------------------------------------------------------------------------\n"
            "$rect = New-Object Win32WindowCore+RECT;\n"
            "[Win32WindowCore]::GetWindowRect($hWnd, [ref]$rect) | Out-Null;\n"
            "$w = [Math]::Max(10, $rect.Right - $rect.Left);\n"
            "$h = [Math]::Max(10, $rect.Bottom - $rect.Top);\n"
            "$tempOcr = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), ('winterm_smart_ocr_' + [System.Guid]::NewGuid().ToString('N') + '.png'));\n"
            "try {\n"
            "    $captured = [Win32ScreenCore]::CaptureScreen($tempOcr, $rect.Left, $rect.Top, $w, $h);\n"
            "    if (-not $captured -or -not (Test-Path $tempOcr)) {\n"
            f"        @{{ Success = $False; Strategy = 'OCR_Failed'; Error = 'Could not capture window bitmap for OCR fallback' }} | ConvertTo-Json -Compress;\n"
            "        exit 0;\n"
            "    };\n"
            "    $file = Await-WinRT ([Windows.Storage.StorageFile]::GetFileFromPathAsync($tempOcr)) ([Windows.Storage.StorageFile]);\n"
            "    $stream = Await-WinRT ($file.OpenAsync(0)) ([Windows.Storage.Streams.IRandomAccessStream]);\n"
            "    $decoder = Await-WinRT ([Windows.Graphics.Imaging.BitmapDecoder]::CreateAsync($stream)) ([Windows.Graphics.Imaging.BitmapDecoder]);\n"
            "    $softwareBitmap = Await-WinRT ($decoder.GetSoftwareBitmapAsync()) ([Windows.Graphics.Imaging.SoftwareBitmap]);\n"
            "    $engine = [Windows.Media.Ocr.OcrEngine]::TryCreateFromUserProfileLanguages();\n"
            "    if (-not $engine) {\n"
            "        $null = [Windows.Globalization.Language, Windows.Globalization, ContentType = WindowsRuntime];\n"
            f"        $engine = [Windows.Media.Ocr.OcrEngine]::TryCreateFromLanguage([Windows.Globalization.Language]::new('{clean_lang}'));\n"
            "    };\n"
            "    $ocrResult = Await-WinRT ($engine.RecognizeAsync($softwareBitmap)) ([Windows.Media.Ocr.OcrResult]);\n"
            "    $targetRect = $null;\n"
            "    $matchedLabel = '';\n"
            "    foreach ($line in $ocrResult.Lines) {\n"
            "        if ($line.Text.IndexOf($query, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) {\n"
            "            $minX = 999999; $minY = 999999; $maxX = -1; $maxY = -1;\n"
            "            foreach ($wItem in $line.Words) {\n"
            "                $wrc = $wItem.BoundingRect;\n"
            "                if ($wrc.X -lt $minX) { $minX = [int]$wrc.X };\n"
            "                if ($wrc.Y -lt $minY) { $minY = [int]$wrc.Y };\n"
            "                if (($wrc.X + $wrc.Width) -gt $maxX) { $maxX = [int]($wrc.X + $wrc.Width) };\n"
            "                if (($wrc.Y + $wrc.Height) -gt $maxY) { $maxY = [int]($wrc.Y + $wrc.Height) };\n"
            "            };\n"
            "            $targetRect = @{ X = $minX; Y = $minY; Width = ($maxX - $minX); Height = ($maxY - $minY) };\n"
            "            $matchedLabel = $line.Text;\n"
            "            break;\n"
            "        };\n"
            "    };\n"
            "    if (-not $targetRect) {\n"
            "        foreach ($line in $ocrResult.Lines) {\n"
            "            foreach ($wItem in $line.Words) {\n"
            "                if ($wItem.Text -like \"*$query*\" -or $query -like \"*$($wItem.Text)*\") {\n"
            "                    $wrc = $wItem.BoundingRect;\n"
            "                    $targetRect = @{ X = [int]$wrc.X; Y = [int]$wrc.Y; Width = [int]$wrc.Width; Height = [int]$wrc.Height };\n"
            "                    $matchedLabel = $wItem.Text;\n"
            "                    break;\n"
            "                };\n"
            "            };\n"
            "            if ($targetRect) { break };\n"
            "        };\n"
            "    };\n"
            "    if ($targetRect) {\n"
            "        $relX = [int]($targetRect.X + ($targetRect.Width / 2));\n"
            "        $relY = [int]($targetRect.Y + ($targetRect.Height / 2));\n"
            "        $hoverResult = [Win32MouseCore]::HoverInWindow($hWnd, $relX, $relY, $dwell);\n"
            "        @{\n"
            "            Success = $hoverResult.Success;\n"
            "            Strategy = 'NativeWindowsOCR';\n"
            "            HoveredInCorrectWindow = $hoverResult.HoveredInCorrectWindow;\n"
            "            MatchedWord = $matchedLabel;\n"
            "            RelCoordinates = @{ X = $relX; Y = $relY };\n"
            "            AbsCoordinates = @{ X = $hoverResult.AbsX; Y = $hoverResult.AbsY };\n"
            "            WindowTitle = $foundTitle;\n"
            "            FocusConfirmed = $fgRes.FocusConfirmed;\n"
            "            Error = $hoverResult.Error;\n"
            "        } | ConvertTo-Json -Compress;\n"
            "    } else {\n"
            "        @{\n"
            "            Success = $False;\n"
            "            Query = $query;\n"
            "            Error = 'Element not found via UIAutomation or Native Windows OCR';\n"
            "            WindowTitle = $foundTitle;\n"
            "            FocusConfirmed = $fgRes.FocusConfirmed;\n"
            "        } | ConvertTo-Json -Compress;\n"
            "    };\n"
            "} catch {\n"
            "    @{ Success = $False; Error = $_.Exception.Message } | ConvertTo-Json -Compress;\n"
            "} finally {\n"
            "    try { if (Test-Path $tempOcr) { [System.IO.File]::Delete($tempOcr) } } catch {};\n"
            "}\n"
        )
        return script
