"""Set-of-Mark (SoM) Visual Grounding Engine: High-contrast bounding box and indexed tag overlay for AI agents.

Enables multimodal LLMs (Google Gemini, Claude, GPT-4o) to execute zero-hallucination clicks
by referencing high-contrast numeric tags ([1], [2], [3]) overlaid directly onto UI elements.
"""

import json
from typing import Optional, Dict, Any, List
from winterm.interaction.window_manager import WindowManager
from winterm.interaction.screen import ScreenPerceptionEngine
from winterm.interaction.ui_automation import UIAutomationEngine


class SetOfMarkEngine:
    """Generates visual Set-of-Mark annotations and index mappings for agent perception."""

    GDI_SOM_HELPER = (
        "Add-Type -AssemblyName System.Drawing;\n"
        "function Draw-SetOfMarkAnnotations($srcImagePath, $dstImagePath, $elementsJson) {\n"
        "    $elements = $elementsJson | ConvertFrom-Json;\n"
        "    $imgBytes = [System.IO.File]::ReadAllBytes($srcImagePath);\n"
        "    $ms = [System.IO.MemoryStream]::new($imgBytes);\n"
        "    $bmp = [System.Drawing.Bitmap]::new($ms);\n"
        "    $g = [System.Drawing.Graphics]::FromImage($bmp);\n"
        "    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias;\n"
        "    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit;\n"
        "    \n"
        "    $penColors = @(\n"
        "        [System.Drawing.Color]::FromArgb(255, 0, 229, 255),  # Bright Cyan\n"
        "        [System.Drawing.Color]::FromArgb(255, 118, 255, 3),  # Bright Lime\n"
        "        [System.Drawing.Color]::FromArgb(255, 255, 214, 0),  # Bright Gold\n"
        "        [System.Drawing.Color]::FromArgb(255, 255, 61, 0),   # Bright Orange\n"
        "        [System.Drawing.Color]::FromArgb(255, 213, 0, 249)   # Bright Magenta\n"
        "    );\n"
        "    $font = [System.Drawing.Font]::new('Arial', 9, [System.Drawing.FontStyle]::Bold);\n"
        "    $textBrush = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::White);\n"
        "    $badgeBrush = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(220, 20, 20, 20));\n"
        "    \n"
        "    $tagIndex = 1;\n"
        "    $manifest = [System.Collections.Generic.List[PSCustomObject]]::new();\n"
        "    foreach ($el in $elements) {\n"
        "        $x = [int]$el.X;\n"
        "        $y = [int]$el.Y;\n"
        "        $w = [Math]::Max(4, [int]$el.Width);\n"
        "        $h = [Math]::Max(4, [int]$el.Height);\n"
        "        \n"
        "        $penColor = $penColors[($tagIndex - 1) % $penColors.Count];\n"
        "        $pen = [System.Drawing.Pen]::new($penColor, 2);\n"
        "        $g.DrawRectangle($pen, $x, $y, $w, $h);\n"
        "        $pen.Dispose();\n"
        "        \n"
        "        # Draw numeric tag badge\n"
        "        $tagStr = \"[$tagIndex]\";\n"
        "        $strSize = $g.MeasureString($tagStr, $font);\n"
        "        $badgeW = [Math]::Ceiling($strSize.Width) + 4;\n"
        "        $badgeH = [Math]::Ceiling($strSize.Height) + 2;\n"
        "        $badgeX = [Math]::Max(0, $x);\n"
        "        $badgeY = [Math]::Max(0, $y - $badgeH);\n"
        "        if ($badgeY -lt 2) { $badgeY = $y + 2 };\n"
        "        \n"
        "        $g.FillRectangle($badgeBrush, $badgeX, $badgeY, $badgeW, $badgeH);\n"
        "        $g.DrawString($tagStr, $font, $textBrush, ($badgeX + 2), ($badgeY + 1));\n"
        "        \n"
        "        $cx = [int]($x + ($w / 2));\n"
        "        $cy = [int]($y + ($h / 2));\n"
        "        $manifest.Add([PSCustomObject]@{\n"
        "            Tag = $tagIndex;\n"
        "            Name = $el.Name;\n"
        "            ControlType = $el.ControlType;\n"
        "            AutomationId = $el.AutomationId;\n"
        "            X = $x;\n"
        "            Y = $y;\n"
        "            Width = $w;\n"
        "            Height = $h;\n"
        "            CenterX = $cx;\n"
        "            CenterY = $cy;\n"
        "        });\n"
        "        $tagIndex++;\n"
        "    };\n"
        "    \n"
        "    $bmp.Save($dstImagePath, [System.Drawing.Imaging.ImageFormat]::Png);\n"
        "    $font.Dispose();\n"
        "    $textBrush.Dispose();\n"
        "    $badgeBrush.Dispose();\n"
        "    $g.Dispose();\n"
        "    $bmp.Dispose();\n"
        "    $ms.Dispose();\n"
        "    return $manifest;\n"
        "}\n"
    )

    @classmethod
    def build_annotate_window_command(
        cls,
        window_identifier: str,
        output_annotated_path: str,
        max_marks: int = 50,
    ) -> str:
        """Inspects target window interactive elements, captures its screenshot, overlays Set-of-Mark tags, and returns index dictionary."""
        clean_target = window_identifier.replace("'", "''")
        clean_output = output_annotated_path.replace("'", "''").replace('"', '""')

        script = (
            f"{WindowManager.WIN32_WINDOW_HELPER}\n"
            f"{ScreenPerceptionEngine.WIN32_SCREEN_HEADER}\n"
            f"{UIAutomationEngine.UIA_HEADER}\n"
            f"{cls.GDI_SOM_HELPER}\n"
            "$foundTitle = '';\n"
            f"$hWnd = [Win32WindowCore]::ResolveWindow('{clean_target}', [ref]$foundTitle);\n"
            "if ($hWnd -eq [IntPtr]::Zero) {\n"
            f"    @{{ Success = $False; Target = '{clean_target}'; Error = 'Target window not found' }} | ConvertTo-Json -Compress;\n"
            "    exit 0;\n"
            "};\n"
            "$rect = New-Object Win32WindowCore+RECT;\n"
            "[Win32WindowCore]::GetWindowRect($hWnd, [ref]$rect) | Out-Null;\n"
            "$w = [Math]::Max(10, $rect.Right - $rect.Left);\n"
            "$h = [Math]::Max(10, $rect.Bottom - $rect.Top);\n"
            "$tempRaw = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), ('winterm_raw_' + [System.Guid]::NewGuid().ToString('N') + '.png'));\n"
            "try {\n"
            "    $captured = [Win32ScreenCore]::CaptureScreen($tempRaw, $rect.Left, $rect.Top, $w, $h);\n"
            "    if (-not $captured -or -not (Test-Path $tempRaw)) {\n"
            "        @{ Success = $False; Error = 'Failed to capture window snapshot for Set-of-Mark' } | ConvertTo-Json -Compress;\n"
            "        exit 0;\n"
            "    };\n"
            "    \n"
            "    # Discover interactive UI Automation descendants\n"
            "    $elem = [System.Windows.Automation.AutomationElement]::FromHandle($hWnd);\n"
            "    $descendants = $elem.FindAll(\n"
            "        [System.Windows.Automation.TreeScope]::Descendants,\n"
            "        [System.Windows.Automation.Condition]::TrueCondition\n"
            "    );\n"
            "    \n"
            "    $candidates = [System.Collections.Generic.List[PSCustomObject]]::new();\n"
            "    foreach ($d in $descendants) {\n"
            f"        if ($candidates.Count -ge {max_marks}) {{ break }};\n"
            "        try {\n"
            "            $cur = $d.Current;\n"
            "            $rc = $cur.BoundingRectangle;\n"
            "            if ($rc.Width -gt 8 -and $rc.Height -gt 8) {\n"
            "                # Translate global screen coordinates to window-relative coordinates\n"
            "                $relX = [int]($rc.X - $rect.Left);\n"
            "                $relY = [int]($rc.Y - $rect.Top);\n"
            "                if ($relX -ge 0 -and $relY -ge 0 -and $relX -lt $w -and $relY -lt $h) {\n"
            "                    $ctrlType = $cur.ControlType.ProgrammaticName.Replace('ControlType.', '');\n"
            "                    if ($cur.Name -or $cur.AutomationId -or $ctrlType -in @('Button', 'Edit', 'MenuItem', 'CheckBox', 'Hyperlink', 'TabItem')) {\n"
            "                        $candidates.Add([PSCustomObject]@{\n"
            "                            Name = if ($cur.Name) { $cur.Name } else { $ctrlType };\n"
            "                            ControlType = $ctrlType;\n"
            "                            AutomationId = $cur.AutomationId;\n"
            "                            X = $relX;\n"
            "                            Y = $relY;\n"
            "                            Width = [int]$rc.Width;\n"
            "                            Height = [int]$rc.Height;\n"
            "                        });\n"
            "                    }\n"
            "                }\n"
            "            }\n"
            "        } catch {}\n"
            "    };\n"
            "    \n"
            "    $candidatesJson = $candidates | ConvertTo-Json -Compress;\n"
            f"    $manifest = Draw-SetOfMarkAnnotations $tempRaw '{clean_output}' $candidatesJson;\n"
            "    \n"
            "    @{\n"
            "        Success = $True;\n"
            "        WindowTitle = $foundTitle;\n"
            "        WindowHandle = $hWnd.ToInt64();\n"
            f"        AnnotatedImagePath = '{clean_output}';\n"
            "        MarksCount = $manifest.Count;\n"
            "        Marks = $manifest;\n"
            "    } | ConvertTo-Json -Compress -Depth 4;\n"
            "} catch {\n"
            "    @{ Success = $False; WindowTitle = $foundTitle; Error = $_.Exception.Message } | ConvertTo-Json -Compress;\n"
            "} finally {\n"
            "    try { if (Test-Path $tempRaw) { [System.IO.File]::Delete($tempRaw) } } catch {};\n"
            "}\n"
        )
        return script
