"""Windows Window Manager: Enumerate, focus, resize, move, and control application windows via Win32."""

import json
from typing import Optional, List, Dict, Any


class WindowManager:
    """Provides programmatic control over top-level Windows application windows using user32.dll and OpenInputDesktop."""

    WIN32_WINDOW_HELPER = (
        "$codeWin = @'\n"
        "using System;\n"
        "using System.Collections.Generic;\n"
        "using System.Diagnostics;\n"
        "using System.Runtime.InteropServices;\n"
        "using System.Text;\n"
        "\n"
        "public class WindowInfo {\n"
        "    public long Handle;\n"
        "    public string Title;\n"
        "    public int ProcessId;\n"
        "    public string ProcessName;\n"
        "    public int X;\n"
        "    public int Y;\n"
        "    public int Width;\n"
        "    public int Height;\n"
        "    public string State;\n"
        "}\n"
        "\n"
        "public class Win32WindowCore {\n"
        "    [StructLayout(LayoutKind.Sequential)]\n"
        "    public struct RECT { public int Left; public int Top; public int Right; public int Bottom; }\n"
        "    [StructLayout(LayoutKind.Sequential)]\n"
        "    public struct WINDOWPLACEMENT {\n"
        "        public int length;\n"
        "        public int flags;\n"
        "        public int showCmd;\n"
        "        public System.Drawing.Point ptMinPosition;\n"
        "        public System.Drawing.Point ptMaxPosition;\n"
        "        public RECT rcNormalPosition;\n"
        "    }\n"
        "\n"
        "    [UnmanagedFunctionPointer(CallingConvention.Winapi)]\n"
        "    public delegate bool EnumWindowsProc(IntPtr hWnd, IntPtr lParam);\n"
        "\n"
        "    [DllImport(\"user32.dll\", SetLastError = true)]\n"
        "    public static extern IntPtr OpenDesktop(string lpszDesktop, uint dwFlags, bool fInherit, uint dwDesiredAccess);\n"
        "    [DllImport(\"user32.dll\", SetLastError = true)]\n"
        "    public static extern bool SetThreadDesktop(IntPtr hDesktop);\n"
        "    [DllImport(\"user32.dll\")] public static extern bool SetProcessDPIAware();\n"
        "    [DllImport(\"user32.dll\")]\n"
        "    public static extern bool EnumThreadWindows(int dwThreadId, EnumWindowsProc lpfn, IntPtr lParam);\n"
        "    [DllImport(\"user32.dll\", SetLastError = true)]\n"
        "    public static extern bool EnumDesktopWindows(IntPtr hDesktop, EnumWindowsProc lpfn, IntPtr lParam);\n"
        "    [DllImport(\"user32.dll\", SetLastError = true)]\n"
        "    public static extern bool EnumWindows(EnumWindowsProc lpfn, IntPtr lParam);\n"
        "    [DllImport(\"user32.dll\", SetLastError = true)]\n"
        "    public static extern IntPtr OpenInputDesktop(uint dwFlags, bool fInherit, uint dwDesiredAccess);\n"
        "    [DllImport(\"user32.dll\", SetLastError = true)]\n"
        "    public static extern bool CloseDesktop(IntPtr hDesktop);\n"
        "    [DllImport(\"user32.dll\")] public static extern bool IsWindowVisible(IntPtr hWnd);\n"
        "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto, SetLastError = true)]\n"
        "    public static extern int GetWindowText(IntPtr hWnd, StringBuilder lpString, int nMaxCount);\n"
        "    [DllImport(\"user32.dll\")] public static extern int GetWindowTextLength(IntPtr hWnd);\n"
        "    [DllImport(\"user32.dll\")] public static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint lpdwProcessId);\n"
        "    [DllImport(\"user32.dll\")] public static extern bool GetWindowRect(IntPtr hWnd, out RECT lpRect);\n"
        "    [DllImport(\"user32.dll\")] public static extern bool GetWindowPlacement(IntPtr hWnd, ref WINDOWPLACEMENT lpwndpl);\n"
        "    [DllImport(\"user32.dll\")] public static extern bool SetForegroundWindow(IntPtr hWnd);\n"
        "    [DllImport(\"user32.dll\")] public static extern bool BringWindowToTop(IntPtr hWnd);\n"
        "    [DllImport(\"user32.dll\")] public static extern void keybd_event(byte bVk, byte bScan, uint dwFlags, int dwExtraInfo);\n"
        "    [DllImport(\"user32.dll\")] public static extern void SwitchToThisWindow(IntPtr hWnd, bool fAltTab);\n"
        "    [DllImport(\"user32.dll\")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);\n"
        "    [DllImport(\"user32.dll\")] public static extern bool MoveWindow(IntPtr hWnd, int X, int Y, int nWidth, int nHeight, bool bRepaint);\n"
        "    [DllImport(\"user32.dll\")] public static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int X, int Y, int cx, int cy, uint uFlags);\n"
        "    [DllImport(\"user32.dll\")] public static extern IntPtr SendMessage(IntPtr hWnd, uint Msg, IntPtr wParam, IntPtr lParam);\n"
        "\n"
        "    public static bool ForceForeground(IntPtr hWnd) {\n"
        "        if (hWnd == IntPtr.Zero) return false;\n"
        "        try {\n"
        "            IntPtr defaultDesk = OpenDesktop(\"default\", 0, false, 0x01FF);\n"
        "            if (defaultDesk != IntPtr.Zero) {\n"
        "                SetThreadDesktop(defaultDesk);\n"
        "            }\n"
        "        } catch {}\n"
        "        try { SetProcessDPIAware(); } catch {}\n"
        "        ShowWindow(hWnd, 9); // SW_RESTORE\n"
        "        BringWindowToTop(hWnd);\n"
        "        // Force window over any IDE or fullscreen applications\n"
        "        SetWindowPos(hWnd, new IntPtr(-1), 0, 0, 0, 0, 0x0001 | 0x0002 | 0x0040); // HWND_TOPMOST\n"
        "        keybd_event(0x12, 0, 0, 0);\n"
        "        keybd_event(0x12, 0, 2, 0);\n"
        "        SetForegroundWindow(hWnd);\n"
        "        SwitchToThisWindow(hWnd, true);\n"
        "        SetWindowPos(hWnd, new IntPtr(-2), 0, 0, 0, 0, 0x0001 | 0x0002 | 0x0040); // HWND_NOTOPMOST\n"
        "        return true;\n"
        "    }\n"
        "\n"
        "    public static bool ResizeMoveWindow(IntPtr hWnd, int x, int y, int width, int height) {\n"
        "        if (hWnd == IntPtr.Zero) return false;\n"
        "        ShowWindow(hWnd, 9);\n"
        "        bool ok = MoveWindow(hWnd, x, y, width, height, true);\n"
        "        if (!ok) {\n"
        "            ok = SetWindowPos(hWnd, IntPtr.Zero, x, y, width, height, 0x0004 | 0x0040);\n"
        "        }\n"
        "        return ok;\n"
        "    }\n"
        "\n"
        "    public static List<WindowInfo> GetVisibleWindows(string filter) {\n"
        "        var results = new List<WindowInfo>();\n"
        "        var seen = new HashSet<long>();\n"
        "        try { SetProcessDPIAware(); } catch {}\n"
        "        try {\n"
        "            IntPtr defaultDesk = OpenDesktop(\"Default\", 0, false, 0x01FF);\n"
        "            if (defaultDesk == IntPtr.Zero) {\n"
        "                defaultDesk = OpenDesktop(\"default\", 0, false, 0x01FF);\n"
        "            }\n"
        "            if (defaultDesk != IntPtr.Zero) {\n"
        "                SetThreadDesktop(defaultDesk);\n"
        "            }\n"
        "        } catch {}\n"
        "\n"
        "        IntPtr desk = OpenInputDesktop(0, false, 0x0100);\n"
        "        EnumWindowsProc callback = (hWnd, lParam) => {\n"
        "            if (!IsWindowVisible(hWnd)) return true;\n"
        "            long hVal = hWnd.ToInt64();\n"
        "            if (seen.Contains(hVal)) return true;\n"
        "            int len = GetWindowTextLength(hWnd);\n"
        "            if (len == 0) return true;\n"
        "            var sb = new StringBuilder(len + 1);\n"
        "            GetWindowText(hWnd, sb, sb.Capacity);\n"
        "            string title = sb.ToString();\n"
        "\n"
        "            uint pid = 0;\n"
        "            GetWindowThreadProcessId(hWnd, out pid);\n"
        "            string procName = \"\";\n"
        "            try {\n"
        "                using (var p = Process.GetProcessById((int)pid)) {\n"
        "                    procName = p.ProcessName;\n"
        "                }\n"
        "            } catch {}\n"
        "\n"
        "            if (!string.IsNullOrEmpty(filter)) {\n"
        "                bool match = title.IndexOf(filter, StringComparison.OrdinalIgnoreCase) >= 0 ||\n"
        "                             procName.IndexOf(filter, StringComparison.OrdinalIgnoreCase) >= 0;\n"
        "                if (!match) return true;\n"
        "            }\n"
        "\n"
        "            RECT rect;\n"
        "            GetWindowRect(hWnd, out rect);\n"
        "            int width = rect.Right - rect.Left;\n"
        "            int height = rect.Bottom - rect.Top;\n"
        "            if (width <= 1 || height <= 1) return true;\n"
        "\n"
        "            var wp = new WINDOWPLACEMENT();\n"
        "            wp.length = Marshal.SizeOf(wp);\n"
        "            GetWindowPlacement(hWnd, ref wp);\n"
        "            string state = wp.showCmd == 2 ? \"Minimized\" : (wp.showCmd == 3 ? \"Maximized\" : \"Normal\");\n"
        "\n"
        "            seen.Add(hVal);\n"
        "            results.Add(new WindowInfo {\n"
        "                Handle = hVal,\n"
        "                Title = title,\n"
        "                ProcessId = (int)pid,\n"
        "                ProcessName = procName,\n"
        "                X = rect.Left,\n"
        "                Y = rect.Top,\n"
        "                Width = width,\n"
        "                Height = height,\n"
        "                State = state\n"
        "            });\n"
        "            return true;\n"
        "        };\n"
        "\n"
        "        try {\n"
        "            IntPtr dDesk = OpenDesktop(\"Default\", 0, false, 0x01FF);\n"
        "            if (dDesk == IntPtr.Zero) {\n"
        "                dDesk = OpenDesktop(\"default\", 0, false, 0x01FF);\n"
        "            }\n"
        "            if (dDesk != IntPtr.Zero) {\n"
        "                try {\n"
        "                    EnumDesktopWindows(dDesk, callback, IntPtr.Zero);\n"
        "                } finally {\n"
        "                    CloseDesktop(dDesk);\n"
        "                }\n"
        "            }\n"
        "        } catch {}\n"
        "\n"
        "        if (desk != IntPtr.Zero) {\n"
        "            try {\n"
        "                EnumDesktopWindows(desk, callback, IntPtr.Zero);\n"
        "            } finally {\n"
        "                CloseDesktop(desk);\n"
        "            }\n"
        "        } else {\n"
        "            EnumWindows(callback, IntPtr.Zero);\n"
        "        }\n"
        "\n"
        "        // Check thread windows for matching or running processes (supports modern Windows 11 UWP apps)\n"
        "        try {\n"
        "            Process[] procs = string.IsNullOrEmpty(filter) ? Process.GetProcesses() : Process.GetProcessesByName(filter.Replace(\".exe\", \"\"));\n"
        "            foreach (var p in procs) {\n"
        "                try {\n"
        "                    foreach (ProcessThread t in p.Threads) {\n"
        "                        EnumThreadWindows(t.Id, callback, IntPtr.Zero);\n"
        "                    }\n"
        "                } catch {}\n"
        "            }\n"
        "        } catch {}\n"
        "\n"
        "        return results;\n"
        "    }\n"
        "\n"
        "    public static IntPtr ResolveWindow(string target, out string outTitle) {\n"
        "        outTitle = \"\";\n"
        "        long hVal = 0;\n"
        "        if (long.TryParse(target, out hVal) && hVal > 1000) {\n"
        "            var all = GetVisibleWindows(\"\");\n"
        "            foreach (var w in all) {\n"
        "                if (w.Handle == hVal) {\n"
        "                    outTitle = w.Title;\n"
        "                    return new IntPtr(w.Handle);\n"
        "                }\n"
        "            }\n"
        "            var h = new IntPtr(hVal);\n"
        "            var sb = new StringBuilder(256);\n"
        "            GetWindowText(h, sb, 256);\n"
        "            outTitle = sb.ToString();\n"
        "            return h;\n"
        "        }\n"
        "        var list = GetVisibleWindows(target);\n"
        "        if (list.Count > 0) {\n"
        "            outTitle = list[0].Title;\n"
        "            return new IntPtr(list[0].Handle);\n"
        "        }\n"
        "        return IntPtr.Zero;\n"
        "    }\n"
        "}\n"
        "'@\n"
        "if (-not ([System.Management.Automation.PSTypeName]'Win32WindowCore').Type) { Add-Type -TypeDefinition $codeWin -ReferencedAssemblies 'System.Drawing' }; "
    )

    @classmethod
    def build_list_windows_command(cls, query: Optional[str] = None) -> str:
        """Generates PowerShell command to enumerate all visible top-level windows with geometry and state."""
        clean_query = query.replace("'", "''") if query else ""
        script = (
            f"{cls.WIN32_WINDOW_HELPER}"
            f"$wins = [Win32WindowCore]::GetVisibleWindows('{clean_query}'); "
            "@($wins) | ConvertTo-Json -Compress"
        )
        return script

    @classmethod
    def build_focus_command(cls, identifier: Any) -> str:
        """Generates PowerShell command to bring a window to the foreground and restore if minimized."""
        clean_target = str(identifier).replace("'", "''")
        script = (
            f"{cls.WIN32_WINDOW_HELPER}"
            "$foundTitle = ''; "
            f"$hWnd = [Win32WindowCore]::ResolveWindow('{clean_target}', [ref]$foundTitle); "
            "if ($hWnd -ne [IntPtr]::Zero) { "
            "    $ok = [Win32WindowCore]::ForceForeground($hWnd); "
            "    @{ Success = $ok; Handle = $hWnd.ToInt64(); Title = $foundTitle; Action = 'FocusWindow' } | ConvertTo-Json -Compress "
            "} else { "
            f"    @{{ Success = $False; Target = '{clean_target}'; Error = 'Window not found' }} | ConvertTo-Json -Compress "
            "}"
        )
        return script

    @classmethod
    def build_resize_move_command(
        cls,
        identifier: Any,
        x: int,
        y: int,
        width: int,
        height: int,
    ) -> str:
        """Generates PowerShell command to reposition and resize a window."""
        clean_target = str(identifier).replace("'", "''")
        script = (
            f"{cls.WIN32_WINDOW_HELPER}"
            "$foundTitle = ''; "
            f"$hWnd = [Win32WindowCore]::ResolveWindow('{clean_target}', [ref]$foundTitle); "
            "if ($hWnd -ne [IntPtr]::Zero) { "
            f"    $ok = [Win32WindowCore]::ResizeMoveWindow($hWnd, {x}, {y}, {width}, {height}); "
            f"    @{{ Success = $ok; Handle = $hWnd.ToInt64(); Title = $foundTitle; TargetX = {x}; TargetY = {y}; TargetWidth = {width}; TargetHeight = {height} }} | ConvertTo-Json -Compress "
            "} else { "
            f"    @{{ Success = $False; Target = '{clean_target}'; Error = 'Window not found' }} | ConvertTo-Json -Compress "
            "}"
        )
        return script

    @classmethod
    def build_set_state_command(cls, identifier: Any, state: str = "minimize") -> str:
        """Generates PowerShell command to minimize, maximize, or restore a window."""
        clean_target = str(identifier).replace("'", "''")
        n_cmd = 6 if state.lower() == "minimize" else (3 if state.lower() == "maximize" else 9)
        script = (
            f"{cls.WIN32_WINDOW_HELPER}"
            "$foundTitle = ''; "
            f"$hWnd = [Win32WindowCore]::ResolveWindow('{clean_target}', [ref]$foundTitle); "
            "if ($hWnd -ne [IntPtr]::Zero) { "
            f"    $ok = [Win32WindowCore]::ShowWindow($hWnd, {n_cmd}); "
            f"    @{{ Success = $True; Handle = $hWnd.ToInt64(); Title = $foundTitle; State = '{state}' }} | ConvertTo-Json -Compress "
            "} else { "
            f"    @{{ Success = $False; Target = '{clean_target}'; Error = 'Window not found' }} | ConvertTo-Json -Compress "
            "}"
        )
        return script

    @classmethod
    def build_close_window_command(cls, identifier: Any) -> str:
        """Generates PowerShell command to send WM_CLOSE (0x0010) to a window."""
        clean_target = str(identifier).replace("'", "''")
        script = (
            f"{cls.WIN32_WINDOW_HELPER}"
            "$foundTitle = ''; "
            f"$hWnd = [Win32WindowCore]::ResolveWindow('{clean_target}', [ref]$foundTitle); "
            "if ($hWnd -ne [IntPtr]::Zero) { "
            "    [Win32WindowCore]::SendMessage($hWnd, 0x0010, [IntPtr]::Zero, [IntPtr]::Zero) | Out-Null; "
            "    @{ Success = $True; Handle = $hWnd.ToInt64(); Title = $foundTitle; Action = 'WM_CLOSE' } | ConvertTo-Json -Compress "
            "} else { "
            f"    @{{ Success = $False; Target = '{clean_target}'; Error = 'Window not found' }} | ConvertTo-Json -Compress "
            "}"
        )
        return script

    # Aliases for convenience
    generate_list_windows = build_list_windows_command
    generate_focus_window = build_focus_command
    generate_resize_move_window = build_resize_move_command
    generate_close_window = build_close_window_command

